# Generated by Django 3.2 on 2021-05-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField(max_length=10)),
                ('end_date', models.DateField(max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
